version: '3'
services:
  node-api-1:
    build: ./backend/
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env

  react-app-1:
    container_name: react-app
    build: ./frontend/shareme/
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/shareme/.env
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
     - node-api-1
